services:
  tienda-db:
    build: ./db
    container_name: tienda-db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tienda-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-padmin123",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  tienda-backend:
    build: ./backend
    container_name: tienda-backend
    environment:
      - DB_HOST=tienda-db
      - DB_USER=root
      - DB_PASSWORD=admin123
      - DB_NAME=tienda_perritos
      - DB_PORT=3306
    ports:
      - "3001:3001"
    depends_on:
      tienda-db:
        condition: service_healthy
    networks:
      - tienda-network
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://127.0.0.1:3001/api/productos || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  tienda-frontend:
    build: ./frontend
    container_name: tienda-frontend
    ports:
      - "8080:80"
    depends_on:
      tienda-backend:
        condition: service_healthy
    networks:
      - tienda-network

networks:
  tienda-network:
    driver: bridge

volumes:
  dbdata:
